### ISSUE TITLE
Example beachballs on Yosemite

### ISSUE THREAD

**Issue by RepublicOfAppsLLC** [phranck/CCNStatusItem#1]
Hi,

Thanks for making this available!  It looks nice.

However running the example project on Yosemite, it beachballs for 30 seconds every time I click on the status bar item.  This is on a maxed out iMac so I don't think it's a hardware issue.

Any ideas?

Thanks.

**Comment by phranck** [comment]
Hey there!

Yeah, I noticed this behaviour, too. But doesn't have the time to dig in, right now. bizarrely it only happens in this example. In a project I used this control it works as expected. Will investigate it as soon as possible.

Cheers
Frank

PS: Feel free to contribute. (-;

**Comment by RepublicOfAppsLLC** [comment]
Thanks!

**Comment by phranck** [comment]
Did not happen anymore...
-closed
