### ISSUE TITLE
Window resizing

### ISSUE THREAD

**Issue by julianvogels** [phranck/CCNStatusItem#10]
I'm trying to resize the window according to its contents. In my window there's a NSStackView, but the status item window won't scale on the bottom when the stack view content height changes. Depending on the AutoLayout Constraints I set, the content will move but always get clipped one or the other way. The window's bounds stay the same.

I saw that your resizing the window in the `updateWindowFrame` method only on init and when I update the ViewController. The view apparently also resizes with the preferredContentSize, but the method is only called twice (probably also on init and update), and not when I resize the height of the NSStackView. 

Is there any way I can resize the status item window dynamically according to its contents?
I want to accomplish pretty the same thing as shown in the InfoBarStackView example by Apple.

**Comment by CWalig** [comment]
Would it be possible to have an example project?

**Comment by julianvogels** [comment]
I forked the project and modified the code for this to work. Now it's too long ago to remember what exactly I did though..
