### ISSUE TITLE
customizing the button

### ISSUE THREAD

**Issue by bryanl** [phranck/CCNStatusItem#3]
Any plans allowing titles or updating the button with a custom view? I'd like to animate the button when something interesting happens.

**Comment by phranck** [comment]
No plans at the moment. But feel free to implement it and send a pull request. (-;

**Comment by phranck** [comment]
@bryanl Good news: In the next time I will give `CCNStatusItem` support for custom views. Need it by myself for a customer project. (-:

**Comment by phranck** [comment]
Custom view support is now implemented.
