### ISSUE TITLE
The dropHandler option doesn't seem to be implemented

### ISSUE THREAD

**Issue by Dejal** [phranck/CCNStatusItem#6]
Am I missing something?  I see parameters and a property for `dropHandler`, but it doesn't seem to be used anywhere.

**Comment by phranck** [comment]
Hey,

you're correct. The complete implementation is missing. If I find some time it will be implemented. Otherwise... feel free to contribute. (-;

**Comment by Dejal** [comment]
I do need this functionality, so if you have some pointers on how to implement it, I'd be happy to give it a go.

**Comment by Dejal** [comment]
Done; see my pull request.
